### PR TITLE
Pull

### PR DESCRIPTION
**Pull request by webdesignsbytom**
Hope this works

### CODE REVIEW

**Comment by xtombrock** [comment]
my code

**Comment by hubertlemczak** [comment]
### Likes

1. Cat in bag.
2. Good Spacing and centred page.
3. Most areas are interactive/clickable/hover effect.
4. Good responsiveness.

### Improvements

1. Footer lol
2. Maybe remove the border when typing in the search bar.

### Questions

1. Cat in bag?

**Comment by CoderManSam** [comment]
Likes

1. The hovers over everything make it very easy to tell what you're hovering over and is great for readability and accessibility.
2. The semi-transparent home bar at the top looks good as it sticks to the top as you can continue to see some of what's below it.
3.  The responsiveness is great with the left-aside and main sections shrinking as the width of the page reduces.

 Improvements
 
 1. Active states for some links (terms etc. do have them)
 2. Positioning of "terms" etc. section, but it was just a time issue, same with completion of tweets 3-5, again just a time thing
 3. Being very picky, the profile icon at the top is a different size to those in the tweets and looks a little off as a result
 
 Questions
 
 1. How did you get the search bar border to remain once clicked?
 2. I got nothing else, where did you find such a cute kitten?

**Comment by xtombrock** [comment]
> Likes
> 
>     1. The hovers over everything make it very easy to tell what you're hovering over and is great for readability and accessibility.
> 
>     2. The semi-transparent home bar at the top looks good as it sticks to the top as you can continue to see some of what's below it.
> 
>     3. The responsiveness is great with the left-aside and main sections shrinking as the width of the page reduces.
> 
> 
> Improvements
> 
>     1. Active states for some links (terms etc. do have them)
> 
>     2. Positioning of "terms" etc. section, but it was just a time issue, same with completion of tweets 3-5, again just a time thing
> 
>     3. Being very picky, the profile icon at the top is a different size to those in the tweets and looks a little off as a result
> 
> 
> Questions
> 
>     1. How did you get the search bar border to remain once clicked?
> 
>     2. I got nothing else, where did you find such a cute kitten?

**Comment by webdesignsbytom** [comment]
The search bar i didnt really make properly. 
I just had a div set to 'contenteditable' which i know lets you mess with type. its not a text box

**Pull request closed without merging**
